import { defineConfig } from '@unocss/vite';
import presetUno from '@unocss/preset-uno';

export default defineConfig({
  exclude: ['node_modules', 'dist', '.git', '.husky', '.vscode', 'public', 'build', 'mock', './stats.html'],
  presets: [presetUno({ dark: 'class' })],
  shortcuts: {
    'wh-full': 'w-full h-full',
    'flex-center': 'flex justify-center items-center',
    'flex-col-center': 'flex-center flex-col',
    'flex-x-center': 'flex justify-center',
    'flex-y-center': 'flex items-center',
    'i-flex-center': 'inline-flex justify-center items-center',
    'i-flex-x-center': 'inline-flex justify-center',
    'i-flex-y-center': 'inline-flex items-center',
    'flex-col': 'flex flex-col',
    'flex-col-stretch': 'flex-col items-stretch',
    'i-flex-col': 'inline-flex flex-col',
    'i-flex-col-stretch': 'i-flex-col items-stretch',
    'flex-1-hidden': 'flex-1 overflow-hidden',
    'absolute-lt': 'absolute left-0 top-0',
    'absolute-lb': 'absolute left-0 bottom-0',
    'absolute-rt': 'absolute right-0 top-0',
    'absolute-rb': 'absolute right-0 bottom-0',
    'absolute-tl': 'absolute-lt',
    'absolute-tr': 'absolute-rt',
    'absolute-bl': 'absolute-lb',
    'absolute-br': 'absolute-rb',
    'absolute-center': 'absolute-lt flex-center wh-full',
    'fixed-lt': 'fixed left-0 top-0',
    'fixed-lb': 'fixed left-0 bottom-0',
    'fixed-rt': 'fixed right-0 top-0',
    'fixed-rb': 'fixed right-0 bottom-0',
    'fixed-tl': 'fixed-lt',
    'fixed-tr': 'fixed-rt',
    'fixed-bl': 'fixed-lb',
    'fixed-br': 'fixed-rb',
    'fixed-center': 'fixed-lt flex-center wh-full',
    'nowrap-hidden': 'whitespace-nowrap overflow-hidden',
    'ellipsis-text': 'nowrap-hidden overflow-ellipsis',
    'transition-base': 'transition-all duration-300 ease-in-out'
  },
  theme: {
    colors: {
      primary: 'var(--van-primary-color)',
      primary_hover: 'var(--van-primary-color-hover)',
      primary_pressed: 'var(--van-primary-color-pressed)',
      primary_active: 'var(--van-primary-color-active)',
      info: 'var(--van-info-color)',
      info_hover: 'var(--van-info-color-hover)',
      info_pressed: 'var(--van-info-color-pressed)',
      info_active: 'var(--van-info-color-active)',
      success: 'var(--van-success-color)',
      success_hover: 'var(--van-success-color-hover)',
      success_pressed: 'var(--van-success-color-pressed)',
      success_active: 'var(--van-success-color-active)',
      warning: 'var(--van-warning-color)',
      warning_hover: 'var(--van-warning-color-hover)',
      warning_pressed: 'var(--van-warning-color-pressed)',
      warning_active: 'var(--van-warning-color-active)',
      error: 'var(--van-error-color)',
      error_hover: 'var(--van-error-color-hover)',
      error_pressed: 'var(--van-error-color-pressed)',
      error_active: 'var(--van-error-color-active)',
      dark: 'var(--van-background-2)',
      theme_dark:'var(--van-background-2)'
    }
  }
});
